name = "freellmapi-cf"
main = "src/index.ts"
compatibility_date = "2026-06-20"
account_id = "de9cc5da9705c7edf34e7e4e0ac9e360"

[assets]
directory = "./src/dashboard"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "freellmapi-db"
database_id = "15b75f57-9114-4fa6-be0d-f063bb2ed499"

[[kv_namespaces]]
binding = "CACHE"
id = "a66b7659a5e44f5e901c208686d40029"

[triggers]
crons = ["*/5 * * * *"]

[vars]
ENCRYPTION_KEY = "freellmapi-cf-encryption-key-2024"
JWT_SECRET = "freellmapi-cf-jwt-secret-2024-secure"
CATALOG_URL = "https://freellmapi.co/api/catalog"
SITE_TITLE = "freellmapi-cf"